version: '2'
services:
  govway:
    container_name: govway_3.3.13.p1.0_T1
    image: lab.link.it/govway-enterprise:3.3.13.p1.0_T1
    depends_on:
        - database
    ports:
        - 8080:8080
    volumes:
        - ./govway_conf:/etc/govway
        - ./govway_log:/var/log/govway
        - ./opentelemetry-javaagent.jar:/tmp/opentelemetry-javaagent.jar
    environment:
        - GOVWAY_DEFAULT_ENTITY_NAME=Ente
        - GOVWAY_DB_SERVER=pg_govway_3.3.13.p1.0_T1
        - GOVWAY_DB_NAME=govwaydb
        - GOVWAY_DB_USER=govway
        - GOVWAY_DB_PASSWORD=govway
        - GOVWAY_POP_DB_SKIP=false
        - GOVWAY_JVM_AGENT_JAR=/tmp/opentelemetry-javaagent.jar
        - OTEL_SERVICE_NAME="govway-all"
        - OTEL_TRACES_EXPORTER=logging
        - OTEL_METRICS_EXPORTER=logging
        - OTEL_LOGS_EXPORTER=logging

# Decommentare dopo il build dell'immagine batch (usando l'opzione "-a batch")
#  batch_stat_orarie:
#    container_name: govway_batch_3.3.13.p1.0_T1
#    image: linkitaly/govway:enterprise-3.3.13.p1.0_batch_postgres
#    #command: Giornaliere
#    #command: Orarie # << default
#    depends_on:
#        - database
#    environment:
#        - GOVWAY_STAT_DB_SERVER=pg_govway_3.3.13.p1.0_T1
#        - GOVWAY_STAT_DB_NAME=govwaydb
#        - GOVWAY_STAT_DB_USER=govway
#        - GOVWAY_STAT_DB_PASSWORD=govway
#        - GOVWAY_BATCH_USA_CRON=yes
  database:
    container_name: pg_govway_3.3.13.p1.0_T1
    image: postgres:13
    environment:
        - POSTGRES_DB=govwaydb
        - POSTGRES_USER=govway
        - POSTGRES_PASSWORD=govway
